### PR TITLE
Only allow fully-released (non-alpha, non-RC) versions.

### LINKED ISSUE #7: Non-fully-released Node Webkit version breaks downloader
The latest at http://dl.node-webkit.org/ is `v0.12.0-rc1` which breaks the current downloader code:

    >  lein node-webkit-build
    2015-Feb-28 15:34:22 -0600 UnknownHost INFO [node-webkit-build.core] - Reading node-webkit available versions
    2015-Feb-28 15:34:28 -0600 UnknownHost INFO [node-webkit-build.core] - Reading package.json
    2015-Feb-28 15:34:28 -0600 UnknownHost INFO [node-webkit-build.core] - Reading files list
    2015-Feb-28 15:34:28 -0600 UnknownHost INFO [node-webkit-build.core] - Writing package files
    2015-Feb-28 15:34:28 -0600 UnknownHost INFO [node-webkit-build.core] - Building linux32
    2015-Feb-28 15:34:28 -0600 UnknownHost INFO [node-webkit-build.core] - Downloading http://dl.node-webkit.org/v0.12.0/node-webkit-v0.12.0-linux-ia32.tar.gz
    clojure.lang.ExceptionInfo: clj-http: status 404
     at clj_http.client$wrap_exceptions$fn__5299.invoke (client.clj:156)
	clj_http.client$wrap_accept$fn__5443.invoke (client.clj:488)
	clj_http.client$wrap_accept_encoding$fn__5449.invoke (client.clj:502)
	clj_http.client$wrap_content_type$fn__5438.invoke (client.clj:478)
	clj_http.client$wrap_form_params$fn__5489.invoke (client.clj:593)
	clj_http.client$wrap_nested_params$fn__5507.invoke (client.clj:617)
	clj_http.client$wrap_method$fn__5484.invoke (client.clj:576)
	clj_http.cookies$wrap_cookies$fn__3092.invoke (cookies.clj:121)
	clj_http.links$wrap_links$fn__4380.invoke (links.clj:50)
	clj_http.client$wrap_unknown_host$fn__5515.invoke (client.clj:636)
	clj_http.client$get.doInvoke (client.clj:739)
	clojure.lang.RestFn.invoke (RestFn.java:423)
	node_webkit_build.io$download_with_progress.invoke (io.clj:52)
	node_webkit_build.core$ensure_platform.invoke (core.clj:95)
	node_webkit_build.core$build_platform.invoke (core.clj:233)
	clojure.core.protocols/fn (protocols.clj:79)
	clojure.core.protocols$fn__6031$G__6026__6044.invoke (protocols.clj:13)
	clojure.core$reduce.invoke (core.clj:6289)
	node_webkit_build.core$build_platforms.invoke (core.clj:240)
	node_webkit_build.core$build_app.invoke (core.clj:249)
	leiningen.node_webkit_build$node_webkit_build.doInvoke (node_webkit_build.clj:17)
	clojure.lang.RestFn.invoke (RestFn.java:410)
	clojure.lang.Var.invoke (Var.java:379)
	clojure.lang.AFn.applyToHelper (AFn.java:154)
	clojure.lang.Var.applyTo (Var.java:700)
	clojure.core$apply.invoke (core.clj:626)
	leiningen.core.main$partial_task$fn__6094.doInvoke (main.clj:263)
	clojure.lang.RestFn.invoke (RestFn.java:410)
	clojure.lang.AFn.applyToHelper (AFn.java:154)
	clojure.lang.RestFn.applyTo (RestFn.java:132)
	clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
	clojure.lang.RestFn.applyTo (RestFn.java:137)
	clojure.core$apply.invoke (core.clj:626)
	leiningen.core.main$apply_task.invoke (main.clj:313)
	leiningen.core.main$resolve_and_apply.invoke (main.clj:319)
	leiningen.core.main$_main$fn__6160.invoke (main.clj:392)
	leiningen.core.main$_main.doInvoke (main.clj:385)
	clojure.lang.RestFn.invoke (RestFn.java:408)
	clojure.lang.Var.invoke (Var.java:379)
	clojure.lang.AFn.applyToHelper (AFn.java:154)
	clojure.lang.Var.applyTo (Var.java:700)
	clojure.core$apply.invoke (core.clj:624)
	clojure.main$main_opt.invoke (main.clj:315)
	clojure.main$main.doInvoke (main.clj:420)
	clojure.lang.RestFn.invoke (RestFn.java:436)
	clojure.lang.Var.invoke (Var.java:388)
	clojure.lang.AFn.applyToHelper (AFn.java:160)
	clojure.lang.Var.applyTo (Var.java:700)
	clojure.main.main (main.java:37)
	sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
	sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke (Method.java:606)
	org.flatland.drip.Main.invoke (Main.java:117)
	org.flatland.drip.Main.start (Main.java:88)
	org.flatland.drip.Main.main (Main.java:64)

### PR DESCRIPTION
**Pull request by eigenhombre**
Fixes #7.

I tested this at the REPL and also by installing locally.  After making the change, download process works again.

### CODE REVIEW

**Comment by wilkerlucio** [comment]
Hi @eigenhombre,

Thank you very much for the patch, but could you please also add some testing covering the new added code? You will find this function is already being tested here: https://github.com/wilkerlucio/lein-node-webkit-build/blob/master/test/node_webkit_build/versions_test.clj#L6

So it's just a matter of updating the test (you will probably also need to remove the file under the `cassets` folder, it will be auto-generated again for you when you run the tests, then you can commit this updated file as well).

Thanks.

**Comment by blischalk** [comment]
Even with this change it appears to not work as it seems like the naming convention of the node webkit zips have changed to be nwjs prefixed e.g., nwjs-v0.12.0-linux-ia32.tar.gz (as see here: http://dl.nwjs.io/v0.12.0/) instead of the node-webkit prefix naming convention they were following previously e.g., node-webkit-v0.11.6-win-x64.zip (as seen here: node-webkit-v0.11.6-linux-ia32.tar.gz)

**Comment by eigenhombre** [comment]
This did, in fact, work for me when I tried it, but clearly the NW source directory is a moving target.  Perhaps we should ask them to keep symlinks for `stable-latest` and `latest`.

**Comment by wilkerlucio** [comment]
@eigenhombre I did some testing here, and I noticed that the addition on the regex is not causing any effect on the reading of the versions (I compared the readed version with and without it), so, I think we need more investigation on how that worked for you.

@blischalk I just commited a change that should fix the naming problem for v0.12.0+, can you guys please try the version `build-0.1.7-SNAPSHOT` and let me know if it's working?

Here is the changes made: https://github.com/wilkerlucio/lein-node-webkit-build/commit/2beb3d13fd8bc45f1a6ed65389009df5b82c27f3

Thanks.

**Comment by wilkerlucio** [comment]
@eigenhombre @blischalk version `0.1.7` was just released and that must fix the problems with the version name, please let me know if you still have issues regarding it.

Thanks.

**Pull request closed without merging**
