### PR TITLE
Change the url for nwjs downloads

### PR DESCRIPTION
**Pull request by JulianKniephoff**
The server URL for the nwjs downloads seems outdated.

### CODE REVIEW

**Comment by wilkerlucio** [comment]
@JulianKniephoff just wanna let you know that I release a new snapshop version `1.0.8-SNAPSHOT`, you can use that if need, I'm having some issues trying to get my GPG certicates right to deploy a non-snapshot release, I'll do the release as soon as I get my certificates right.

**Comment by JulianKniephoff** [comment]
Alright, thank you! :)

**Comment by wilkerlucio** [comment]
@JulianKniephoff just fwi, version 1.0.8 was just released, please let me know if you have any issues with it.

**Comment by JulianKniephoff** [comment]
Nice, works great. Thanks. :)

**Pull request merged**
